export const ENABLE_LOADER = "ENABLE_LOADER";
export const DISABLE_LOADER = "DISABLE_LOADER";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RESTORE_SESSION = "RESTORE_SESSION";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";